
/**************************************************************
 *	
 *	Item, 8 bit, 11025Hz,
 *	1 channel, 16249 bytes/channel
 *	Total Size: 1 * 16249 + 4 (header) = 16293 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\clare\git\cs2261\finalProject\Item.wav
 *	Time-stamp: Fri Nov 23 16:25:02 2018
 *	
 **************************************************************/

#ifndef __ITEMH__
#define __ITEMH__

#define ITEMFREQ 11025
#define ITEMLEN 16249

extern const unsigned char Item[16249];

#endif /* __ITEMH__ */
