
/**************************************************************
 *	
 *	Spell, 8 bit, 11025Hz,
 *	1 channel, 22850 bytes/channel
 *	Total Size: 1 * 22850 + 4 (header) = 22894 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\clare\git\cs2261\finalProject\Spell.wav
 *	Time-stamp: Fri Nov 23 16:24:53 2018
 *	
 **************************************************************/

#ifndef __SPELLH__
#define __SPELLH__

#define SPELLFREQ 11025
#define SPELLLEN 22850

extern const unsigned char Spell[22850];

#endif /* __SPELLH__ */
