
/**************************************************************
 *	
 *	ThemeSong, 8 bit, 11025Hz,
 *	1 channel, 3316215 bytes/channel
 *	Total Size: 1 * 3316215 + 4 (header) = 3316259 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\clare\git\cs2261\finalProject\ThemeSong.wav
 *	Time-stamp: Fri Nov 23 18:10:27 2018
 *	
 **************************************************************/

#ifndef __THEMESONGH__
#define __THEMESONGH__

#define THEMESONGFREQ 11025
#define THEMESONGLEN 3316215

extern const unsigned char ThemeSong[3316215];

#endif /* __THEMESONGH__ */
